language: scala

scala:
  - 2.12.13
  - 2.13.5
  - 3.0.0-RC1

jdk:
  - openjdk8

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - export NODE_PATH="$(npm config get prefix)"/lib/node_modules
  - npm install
  - npm install jsdom source-map-support

env:
  - TARGET=JVM PRE=test:compile
  - TARGET=JS  PRE=test:fastOptJS

script:
  - sbt ++$TRAVIS_SCALA_VERSION ${TARGET}/$PRE
  - sbt ++$TRAVIS_SCALA_VERSION ${TARGET}/test

before_cache:
  - rm -f $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.sbt -name "*.lock" -type f -delete
cache:
  directories:
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

